export const InfDemoData = {
  nameOfCompany: "Tanwir and Sons",
  sector: "IT",
  hrId: "620b694abfe1449b45d91808",
  website: "tanwir.com",
  duration: [
    "May-July 2022(For ALL Pre-final year students - 2023 Batch)",
    "July - Dec 2022(For Final Year M.Tech/ MBA - Business Analytics students - 2022 Batch)",
  ],
  description:
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum rerum, laboriosam suscipit ipsam illo iste, molestiae quasi quis modi maxime, ad magni fuga nam in iusto perspiciatis doloribus nesciunt aspernatur.",
  designation: "Director",
  mode: "virtual",
  placeOfPosting: "Home",
  btechStudents: [
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Science and Engineering",
    "Electrical Engineering",
    "Electronics and Communication Engineering",
    "Electronics & Instrumentation Engineering",
    "Mechanical Engineering",
    "Engineering Physics",
    "Environmental Engineering",
    "Mineral & Metallurgical Engineering",
    "Mining Engineering",
    "Mining Machinery Engineering",
    "Petroleum Engineering",
  ],
  fiveYrsStudents: [
    "Computer Science & Engineering",
    "Mathematics & Computing",
    "Applied Geology",
    "Applied Geophysics",
  ],
  skillBasedStudents: [
    "C, C++, Java, Python, etc.",
    "Full Stack Development (Frontend/Backend)",
    "AI/ ML/DL, Data Science",
    "Business/Data Analytics, Product Management",
    "Others",
  ],
  mscStudents: ["Chemistry", "Mathematics & Computing", "Physics"],
  msctechStudents: ["Applied Geology", "Applied Geophysics"],
  mtechStudents: [
    "Geo Exploration",
    "Engineering Geology",
    "Earthquake Science & Engineering",
    "Pharmaceutical Science & Engineering",
    "Chemical Engineering",
    "Geotechnical Engineering",
    "Structural Engineering",
    "Computer Science & Engineering",
    "Computer Science & Engineering with Specialization in Information Security",
    "Data Analytics",
    "Power Systems Engineering",
    "Power Electronics & Electrical Drives",
    "Communication & Signal Processing",
    "Optoelectronics & Optical Communication Engineering",
    "RF and Microwave Engineering",
    "VLSI Design",
    "Environmental Science & Engineering",
    "Mineral Engineering",
    "Fuel Engineering",
    "Mining Machinery Engineering",
    "Machine Design",
    "Maintainance Engineering & Tribology",
    "Manufacturing Engineering",
    "Thermal Engineering",
    "Industrial Engineering & Management",
    "Geomatics",
    "Mining Engineering",
    "Opencast Mining",
    "Tunneling & Underground Space Technology",
    "Petroleum Engineering",
  ],
  mbaStudents: [
    "Business Analytics",
    "Finance",
    "Human Resources",
    "Marketing",
    "Operations",
    "General",
  ],
  shortlistFromResumes: true,
  eligibilityCriteria: "kisi ko nahi lenge",
  typeOfTest: "Aptitude",
  otherRounds: ["GD"],
  totalRounds: 2,
  numberOfOffers: 1000,
  stipend: "1,00,00,000",
  provisionForPPO: false,
  ctcDetails: "1 cr per week",
  documents: [],
  _id: "621a71753217fdc998435c88",
  __v: 0,
};
