export const coursesAvailable = {
  btechStudents: [
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Science and Engineering",
    "Electrical Engineering",
    "Electronics and Communication Engineering",
    "Mechanical Engineering",
    "Engineering Physics",
    "Environmental Engineering",
    "Mineral & Metallurgical Engineering",
    "Mining Engineering",
    "Mining Machinery Engineering",
    "Petroleum Engineering",
  ],
  fiveYrsStudents: [
    "Computer Science & Engineering",
    "Mathematics & Computing",
    "Applied Geology",
    "Applied Geophysics",
  ],
  mscStudents: ["Chemistry", "Mathematics & Computing", "Physics"],
  msctechStudents: ["Applied Geology", "Applied Geophysics"],
  mtechStudents: [
    " Applied Geology",
    "Applied Geophysics",
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Science and Engineering",
    "Data Analytics",
    "Electrical Engineering",
    "Electronics & Communication Engineering",
    "Environmental Engineering",
    "Industrial Engineering & Management",
    "Mechanical Engineering",
    "Fuel, Minerals & Metallurgical Engineering",
    "Mining Engineering",
    "Mining Machinery Engineering",
    "Petroleum Engineering",
    "Pharmaceutical Science & Engineering",
  ],
  mbaStudents: [
    "Business Analytics",
    "Finance",
    "Human Resources",
    "Marketing",
    "Operations",
  ],
  skillBasedStudents: [
    "C, C++, Java, Python, etc.",
    "Full Stack Development (Frontend/Backend)",
    "AI/ ML/DL, Data Science",
    "Business/Data Analytics, Product Management",
    "Others",
  ],
};
