export const coursesAvailable = {
  btechStudents: [
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Science and Engineering",
    "Electrical Engineering",
    "Electronics and Communication Engineering",
    "Electronics & Instrumentation Engineering",
    "Mechanical Engineering",
    "Engineering Physics",
    "Environmental Engineering",
    "Mineral & Metallurgical Engineering",
    "Mining Engineering",
    "Mining Machinery Engineering",
    "Petroleum Engineering",
  ],
  fiveYrsStudents: [
    "Computer Science & Engineering",
    "Mathematics & Computing",
    "Applied Geology",
    "Applied Geophysics",
  ],
  mscStudents: ["Chemistry", "Mathematics & Computing", "Physics"],
  msctechStudents: ["Applied Geology", "Applied Geophysics"],
  mtechStudents: [
    "Geo Exploration",
    "Engineering Geology",
    "Earthquake Science & Engineering",
    "Pharmaceutical Science & Engineering",
    "Chemical Engineering",
    "Geotechnical Engineering",
    "Structural Engineering",
    "Computer Science & Engineering",
    "Computer Science & Engineering with Specialization in Information Security",
    "Data Analytics",
    "Power Systems Engineering",
    "Power Electronics & Electrical Drives",
    "Communication & Signal Processing",
    "Optoelectronics & Optical Communication Engineering",
    "RF and Microwave Engineering",
    "VLSI Design",
    "Environmental Science & Engineering",
    "Mineral Engineering",
    "Fuel Engineering",
    "Mining Machinery Engineering",
    "Machine Design",
    "Maintainance Engineering & Tribology",
    "Manufacturing Engineering",
    "Thermal Engineering",
    "Industrial Engineering & Management",
    "Geomatics",
    "Mining Engineering",
    "Opencast Mining",
    "Tunneling & Underground Space Technology",
    "Petroleum Engineering",
  ],
  mbaStudents: [
    "Business Analytics",
    "Finance",
    "Human Resources",
    "Marketing",
    "Operations",
    "General",
  ],
  phdStudents: [
    "Chemistry",
    "Applied Geology",
    "Applied Geophysics",
    "Mathematics & Computing",
    "Physics",
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Science & Engineering",
    "Electrical Engineering",
    "Electronics Engineering",
    "Fuel, Minerals & Metallurgical Engineering",
    "Environmental Science & Engineering",
    "Humanities & Social Sciences",
    "Management Studies",
    "Mechanical Engineering",
    "Mining Machinery Engineering",
    "Mining Engineering",
    "Petroleum Engineering",
  ],
  skillBasedStudents: [
    "C, C++, Java, Python, etc.",
    "Full Stack Development (Frontend/Backend)",
    "AI/ ML/DL, Data Science",
    "Business/Data Analytics, Product Management",
    "Others",
  ],
};
